In [2]:
import numpy

In [3]:
# testing some trigonometric functions from numpy

to_deg = lambda arc: arc * 180.0/numpy.pi
def myatan(x,y):
    return numpy.pi*(1.0-0.5*(1+numpy.sign(x))*(1-numpy.sign(y**2))-0.25*(2+numpy.sign(x))*numpy.sign(y))-numpy.sign(x*y)*numpy.arctan((numpy.abs(x)-numpy.abs(y))/(numpy.abs(x)+numpy.abs(y)))
def myacos(x):
    x[numpy.abs(x) > 1.0] = numpy.round(x[numpy.abs(x) > 1.0])
    return numpy.arccos(x)
def myasin(x):
    x[numpy.abs(x) > 1.0] = numpy.round(x[numpy.abs(x) > 1.0])
    return numpy.arcsin(x)
def is_vector(v,fromnumpy=True):
    try:
        isSingleton = numpy.sum(numpy.asarray(numpy.asarray(v.shape) != 1,dtype=int)) == 1 # there only one dimension that has more than 1 elements
        isShapeLenOne = len(v.shape) == 1
    except AttributeError:
        if (not fromnumpy) and ((type(v) is list) or (type(v) is tuple)):
            return not numpy.isscalar(v)
        isShapeLenOne = False
        isSingleton = False
    return (not numpy.isscalar(v)) and (isShapeLenOne or isSingleton)
def pback(x,v,ascol=True):
    # appends v to the end of x if x is vector
    # if x is a matrix, appends v as column if ascol is True, or as row otherwise
    if is_vector(x):
        if len(x.shape) == 1: # just an array, not col, not row
            return numpy.append(x,v)
        else:
            if x.shape[0] == 1:
                return numpy.append(x,v).reshape((1,x.shape[1]+1))
            else:
                return numpy.append(x,v).reshape((x.shape[0]+1,1))
    else:
        if numpy.isscalar(v):
            if ascol:
                v = v + numpy.zeros((x.shape[0],1))
                axis = 1
            else:
                v = v + numpy.zeros((1,x.shape[1]))
                axis = 0
        return numpy.append(x,v,axis=axis)

# first, we calculate the angle between two vectors
u = numpy.array([0.5,numpy.sqrt(3.0)/2.0])
v = numpy.array([numpy.sqrt(3.0)/2.0,0.5])

theta_u = numpy.arctan2(u[1],u[0])
theta_v = numpy.arctan2(v[1],v[0])

theta_uv_dot = numpy.arccos(numpy.dot(u,v)/(numpy.linalg.norm(u)*numpy.linalg.norm(v)))
theta_uv_cross = numpy.arcsin(numpy.linalg.norm( numpy.cross(pback(u,0),pback(v,0)) )/(numpy.linalg.norm(u)*numpy.linalg.norm(v)))

print('vector u = ' + str(u))
print('    angle with +x = {:g}'.format(to_deg(theta_u)))

print('')

print('vector v = ' + str(v))
print('    angle with +x = {:g}'.format(to_deg(theta_v)))

print('')

print('angle between u and v (expected = 30)')
print('    given by dot product   = {:g}'.format(  to_deg(  theta_uv_dot  )  )  )
print('    given by cross product = {:g}'.format(  to_deg(  theta_uv_cross  )  )  )

vector u = [0.5       0.8660254]
    angle with +x = 60

vector v = [0.8660254 0.5      ]
    angle with +x = 30

angle between u and v (expected = 30)
    given by dot product   = 30
    given by cross product = 30


In [88]:
# testing some trigonometric functions from numpy

# first, we calculate the angle between two vectors
u = numpy.array([[numpy.sqrt(3.0)/2.0,0.5],
                 [0.5,numpy.sqrt(3.0)/2.0],
                 [0.0,1.0],
                 [-0.5,numpy.sqrt(3.0)/2.0],
                 [-numpy.sqrt(3.0)/2.0,0.5],
                 [-1.0,0.0],
                 [-numpy.sqrt(3.0)/2.0,-0.5],
                 [-0.5,-numpy.sqrt(3.0)/2.0],
                 [0.0,-1.0],
                 [0.5,-numpy.sqrt(3.0)/2.0],
                 [numpy.sqrt(3.0)/2.0,-0.5],
                 [1.0,0.0]])
v = numpy.array([numpy.sqrt(3.0)/2.0,0.5])

theta_u = myatan(u[:,0],u[:,1])
theta_v = numpy.arctan2(v[1],v[0])

theta_uv_exp = theta_u - theta_v

theta_uv_dot = myacos(numpy.dot(u,v)/(numpy.linalg.norm(u,axis=1)*numpy.linalg.norm(v)))
theta_uv_cross = myasin(numpy.linalg.norm( numpy.cross(pback(u,0),pback(v,0)), axis=1 )/(numpy.linalg.norm(u,axis=1)*numpy.linalg.norm(v)))

print('vector v = ' + str(v))
print('    angle with +x = {:g}'.format(to_deg(theta_v)))
print('')
print('each u vector angles with +x')
print(to_deg(theta_u))
print('')
print('expected angles between u and v: th_u - th_v')
print(to_deg(theta_uv_exp))
print('')
print('angles from u.v:')
print(to_deg(theta_uv_dot))
print('')
print('angles from u x v:')
print(to_deg(theta_uv_cross))

vector v = [0.8660254 0.5      ]
    angle with +x = 30

each u vector angles with +x
[ 30.  60.  90. 120. 150. 180. 210. 240. 270. 300. 330.   0.]

expected angles between u and v: th_u - th_v
[  0.  30.  60.  90. 120. 150. 180. 210. 240. 270. 300. -30.]

angles from u.v:
[  0.  30.  60.  90. 120. 150. 180. 150. 120.  90.  60.  30.]

angles from u x v:
[ 0. 30. 60. 90. 60. 30.  0. 30. 60. 90. 60. 30.]


In [85]:
print(u[1])
print(v)

numpy.linalg.norm(numpy.cross(pback(u,0),pback(v,0)),axis=1)

[0.5       0.8660254]
[0.8660254 0.5      ]


array([0.       , 0.5      , 0.8660254, 1.       , 0.8660254, 0.5      ,
       0.       , 0.5      , 0.8660254, 1.       , 0.8660254, 0.5      ])

In [81]:


pback(numpy.array([1,2,3]),4)
pback(numpy.array([1,2,3]).reshape((1,3)),4)
pback(numpy.array([1,2,3]).reshape((3,1)),4)
pback(numpy.arange(15).reshape((5,3)),4,ascol=True)

array([[ 0.,  1.,  2.,  4.],
       [ 3.,  4.,  5.,  4.],
       [ 6.,  7.,  8.,  4.],
       [ 9., 10., 11.,  4.],
       [12., 13., 14.,  4.]])

In [11]:
numpy.arange(10).astype(float)[numpy.array([],dtype=int)]

array([], dtype=float64)

In [7]:
numpy.logical_not( numpy.arange(10)>2)

array([ True,  True,  True, False, False, False, False, False, False,
       False])